<?php
/**
 * Generated by bin/make-block-assets.php — do not edit by hand.
 *
 * Dependencies are derived from the window.wp.* globals index.js uses.
 * No version key: core falls back to block.json's, which
 * bin/bump-version.php keeps current.
 */

return array(
	'dependencies' => array(
		'wp-block-editor',
		'wp-blocks',
		'wp-components',
		'wp-element',
		'wp-i18n',
	),
);
